### ISSUE TITLE
Fix coverage reports

### ISSUE THREAD

**Issue by AAlon** [aws-robotics/tts-ros2#11]
The [coverage report](https://codecov.io/gh/aws-robotics/tts-ros2) seems unreliable, the figure is ~11% but looking at tests here I highly doubt it's that low (also see [tts-ros1](https://codecov.io/gh/aws-robotics/tts-ros1) which has similar tests and sits at 77%).

There's probably something wrong in the way our coverage reporting works for ROS2 Python packages, need to investigate further.

**Comment by mm318** [comment]
With https://github.com/aws-robotics/travis-scripts/pull/61, the coverage report improved, but I believe we can do better. If the directory structure of this repo is similar to that of `tts-ros1`, it would be easier to exclude `voicer.py` from being part of the coverage report (which `tts-ros1` also excludes).

Let's decide if `voicer.py` should be excluded or not, but if not, we should change `tts-ros1` to include it in its coverage reports, too, to be consistent.

**Comment by mm318** [comment]
We have decided that `voicer.py` should remain included in the coverage reports, so the current coverage rate of 58% is considered accurate.

Closing this issue as the coverage report is now considered accurate.
